# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = tutorials
BUILDDIR      = build

# [NCL] Detect if running on GitHub Actions
# This is important because the output colors generated by executing
# fridadrp in GitHub are based on the use of dark terminals, and these
# colors don't look nice with the white background employed in the
# documentation
ifeq ($(CI),true)
    ON_GITHUB = true
else
    ON_GITHUB = false
endif

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile clean  # [NCL]: added clean to the .PHONY declaration

# [NCL]: create explicit clean target that only runs sphinx-build
clean:
	@$(SPHINXBUILD) -M clean "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
ifneq ($(ON_GITHUB),true)
	@echo "Running preliminary scripts..."
	tutorials/auxiliary_tools/data_cube_mosaics/files/run_extract_blocks_ansi_adr_correction_from_extension_test1b.sh
	tutorials/auxiliary_tools/data_cube_mosaics/files/run_extract_blocks_ansi_adr_correction_from_extension_test1c.sh
	tutorials/auxiliary_tools/data_cube_mosaics/files/run_extract_blocks_ansi_combination_test0_2d.sh
	tutorials/auxiliary_tools/data_cube_mosaics/files/run_extract_blocks_ansi_combination_test0_3d.sh
	tutorials/auxiliary_tools/data_cube_mosaics/files/run_extract_blocks_ansi_combination_test1_3d.sh
	tutorials/auxiliary_tools/data_cube_mosaics/files/run_extract_blocks_ansi_combination_test1_3d_ADR.sh
	tutorials/auxiliary_tools/data_cube_mosaics/files/run_extract_blocks_ansi_compute_adr_wavelength_airmass3.sh
	tutorials/auxiliary_tools/initial_slice_boundaries/files/run_extract_blocks_ansi_find_borders1.sh
	tutorials/auxiliary_tools/initial_slice_boundaries/files/run_extract_blocks_ansi_find_borders2.sh
	tutorials/auxiliary_tools/initial_slice_boundaries/files/run_extract_blocks_ansi_find_borders3.sh
	tutorials/auxiliary_tools/initial_slice_boundaries/files/run_extract_blocks_ansi_find_borders4.sh
	tutorials/auxiliary_tools/initial_slice_boundaries/files/run_extract_blocks_ansi_find_borders5.sh
	tutorials/auxiliary_tools/initial_slice_boundaries/files/run_extract_blocks_ansi_find_borders6.sh
	tutorials/auxiliary_tools/initial_slice_boundaries/files/run_extract_blocks_ansi_find_borders7.sh
	tutorials/auxiliary_tools/initial_slice_boundaries/files/run_extract_blocks_ansi_find_traces1.sh
	tutorials/auxiliary_tools/initial_slice_boundaries/files/run_extract_blocks_ansi_find_traces2.sh
	tutorials/auxiliary_tools/initial_slice_boundaries/files/run_extract_blocks_ansi_helps.sh
	tutorials/ifu_simulator/files/run_extract_blocks_ansi_version.sh
	tutorials/ifu_simulator/files/run_extract_blocks_ansi_helps.sh
else
	@echo "Skipping preliminary scripts (GitHub build, using committed files)..."
endif
	@echo "Generating documentation now..."
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
